apiVersion: xl-deploy/v1beta1
kind: Applications
spec:
- name: ecommerce
  type: core.Directory
  children:
    - name: ecommerce-app-service
      type: udm.Application
      children:
      - name: '1.0'
        type: udm.DeploymentPackage
        deployables:
        - name: ecommerce-registry
          type: aws.ecs.ServiceSpec
          serviceName: ecommerce-registry
          desiredCount: 1
          launchType: FARGATE
          networkMode: awsvpc
          assignPublicIp: true
          cpu: 1024
          memory: 2048
          subnets:
          - 'Name:{{username}}-ecommerce-ecs-subnet-ipv4-az-1a'
          - 'Name:{{username}}-ecommerce-ecs-subnet-ipv4-az-1b'
          securityGroups:
          - 'Name:{{username}}-ecommerce-ecs-security-group'
          containerDefinitions:
          - name: ecommerce-registry
            containerName: ecommerce-registry
            type: aws.ecs.ContainerDefinitionSpec
            image: jhipster/jhipster-registry:v4.0.0
            cpu: 1024
            softMemoryLimit: 768
            portMappings:
            - name: port-mapping-8761
              type: aws.ecs.PortSpec
              containerPort: 8761
            environment:
              SPRING_PROFILES_ACTIVE: dev
              SPRING_SECURITY_USER_PASSWORD: admin
              JHIPSTER_REGISTRY_PASSWORD: admin
              SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE: native
              SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS: file:./central-config
              JHIPSTER_LOGGING_LOGSTASH_ENABLED: true
              JHIPSTER_LOGGING_LOGSTASH_HOST: jhipster-logstash
              JHIPSTER_METRICS_LOGS_ENABLED: true
              JHIPSTER_METRICS_LOGS_REPORTFREQUENCY: 60
            logConfiguration:
            - name: cloudwatch-log-registry
              type: aws.ecs.LogConfigurationSpec
              logDriver: awslogs
              options:
                awslogs-group: "/ecs/test"
                awslogs-region: "{{region}}"
                awslogs-stream-prefix: "ecs"
        - name: ecommerce-store-app
          type: aws.ecs.ServiceSpec
          serviceName: ecommerce-store-app
          desiredCount: 1
          launchType: FARGATE
          networkMode: awsvpc
          assignPublicIp: true
          cpu: 1024
          memory: 2048
          subnets:
          - 'Name:{{username}}-ecommerce-ecs-subnet-ipv4-az-1a'
          - 'Name:{{username}}-ecommerce-ecs-subnet-ipv4-az-1b'
          securityGroups:
          - 'Name:{{username}}-ecommerce-ecs-security-group'
          containerDefinitions:
          - name: ecommerce-store-app
            containerName: ecommerce-store-app
            type: aws.ecs.ContainerDefinitionSpec
            image: xebialabsunsupported/ecommerce-store
            cpu: 1024
            softMemoryLimit: 768
            portMappings:
            - name: port-mapping-8080
              type: aws.ecs.PortSpec
              containerPort: 8080
            environment:
              SPRING_PROFILES_ACTIVE: prod,swagger
              EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
              SPRING_CLOUD_CONFIG_URI: http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
              SPRING_DATASOURCE_URL: jdbc:mysql://store-mysql:3306/store?useUnicode=true&characterEncoding=utf8&useSSL=false
              JHIPSTER_SLEEP: 30
              JHIPSTER_REGISTRY_PASSWORD: admin
        - name: ecommerce-store-db
          type: aws.ecs.ServiceSpec
          serviceName: ecommerce-store-db
          desiredCount: 1
          launchType: FARGATE
          networkMode: awsvpc
          assignPublicIp: true
          cpu: 1024
          memory: 2048
          subnets:
          - 'Name:{{username}}-ecommerce-ecs-subnet-ipv4-az-1a'
          - 'Name:{{username}}-ecommerce-ecs-subnet-ipv4-az-1b'
          securityGroups:
          - 'Name:{{username}}-ecommerce-ecs-security-group'
          containerDefinitions:
          - name: ecommerce-store-mysql
            containerName: ecommerce-store-mysql
            type: aws.ecs.ContainerDefinitionSpec
            image: mysql:5.7.20
            cpu: 1024
            softMemoryLimit: 768
            environment:
              MYSQL_USER: root
              MYSQL_ALLOW_EMPTY_PASSWORD: yes
              MYSQL_DATABASE: store
            #command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
        - name: ecommerce-invoice-app
          type: aws.ecs.ServiceSpec
          serviceName: ecommerce-invoice-app
          desiredCount: 1
          launchType: FARGATE
          networkMode: awsvpc
          assignPublicIp: true
          cpu: 1024
          memory: 2048
          subnets:
          - 'Name:{{username}}-ecommerce-ecs-subnet-ipv4-az-1a'
          - 'Name:{{username}}-ecommerce-ecs-subnet-ipv4-az-1b'
          securityGroups:
          - 'Name:{{username}}-ecommerce-ecs-security-group'
          containerDefinitions:
          - name: ecommerce-invoice-app
            containerName: ecommerce-invoice-app
            type: aws.ecs.ContainerDefinitionSpec
            image: xebialabsunsupported/ecommerce-invoice
            cpu: 512
            softMemoryLimit: 768
        - name: ecommerce-invoice-db
          type: aws.ecs.ServiceSpec
          serviceName: ecommerce-invoice-db
          desiredCount: 1
          launchType: FARGATE
          networkMode: awsvpc
          assignPublicIp: true
          cpu: 1024
          memory: 2048
          subnets:
          - 'Name:{{username}}-ecommerce-ecs-subnet-ipv4-az-1a'
          - 'Name:{{username}}-ecommerce-ecs-subnet-ipv4-az-1b'
          securityGroups:
          - 'Name:{{username}}-ecommerce-ecs-security-group'
          containerDefinitions:
          - name: ecommerce-invoice-mysql
            containerName: ecommerce-invoice-mysql
            type: aws.ecs.ContainerDefinitionSpec
            image: mysql:5.7.20
            cpu: 512
            softMemoryLimit: 768
            environment:
              MYSQL_USER: root
              MYSQL_ALLOW_EMPTY_PASSWORD: yes
              MYSQL_DATABASE: invoice
            #command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
        - name: ecommerce-notification-app
          type: aws.ecs.ServiceSpec
          serviceName: ecommerce-notification-app
          desiredCount: 1
          launchType: FARGATE
          networkMode: awsvpc
          assignPublicIp: true
          cpu: 1024
          memory: 2048
          subnets:
          - 'Name:{{username}}-ecommerce-ecs-subnet-ipv4-az-1a'
          - 'Name:{{username}}-ecommerce-ecs-subnet-ipv4-az-1b'
          securityGroups:
          - 'Name:{{username}}-ecommerce-ecs-security-group'
          containerDefinitions:
          - name: ecommerce-notification-app
            containerName: ecommerce-notification-app
            type: aws.ecs.ContainerDefinitionSpec
            image: xebialabsunsupported/ecommerce-notification
            cpu: 512
            softMemoryLimit: 768
            environment:
              SPRING_PROFILES_ACTIVE: prod,swagger
              EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
              SPRING_CLOUD_CONFIG_URI: http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
              SPRING_DATA_MONGODB_URI: mongodb://notification-mongodb:27017
              SPRING_DATA_MONGODB_DATABASE: notification
              JHIPSTER_SLEEP: 30
              JHIPSTER_REGISTRY_PASSWORD: admin
        - name: ecommerce-notification-db
          type: aws.ecs.ServiceSpec
          serviceName: ecommerce-notification-db
          desiredCount: 1
          launchType: FARGATE
          networkMode: awsvpc
          assignPublicIp: true
          cpu: 1024
          memory: 2048
          subnets:
          - 'Name:{{username}}-ecommerce-ecs-subnet-ipv4-az-1a'
          - 'Name:{{username}}-ecommerce-ecs-subnet-ipv4-az-1b'
          securityGroups:
          - 'Name:{{username}}-ecommerce-ecs-security-group'
          containerDefinitions:
          - name: ecommerce-notification-mongodb
            containerName: ecommerce-notification-mongodb
            type: aws.ecs.ContainerDefinitionSpec
            image: mongo:3.6.3
            cpu: 512
            softMemoryLimit: 768