apiVersion: xl-deploy/v1beta1
kind: Applications
spec:
- name: ecommerce
  type: core.Directory
  children:
    - name: ecommerce-app-service
      type: udm.Application
      children:
      - name: '1.0'
        type: udm.DeploymentPackage
        deployables:
        - name: jhipster-registry
          type: aws.ecs.ServiceSpec
          serviceName: jhipster-registry
          desiredCount: 1
          launchType: FARGATE
          networkMode: awsvpc
          assignPublicIp: true
          cpu: 1024
          memory: 2048
          executionRole: 'arn:aws:iam::932770550094:role/ecsTaskExecutionRole'
          subnets:
          - 'Name:{{username}}-ecommerce-ecs-subnet-ipv4-az-1a'
          - 'Name:{{username}}-ecommerce-ecs-subnet-ipv4-az-1b'
          securityGroups:
          - 'Name:{{username}}-ecommerce-ecs-security-group'
          containerDefinitions:
          - name: jhipster-registry
            containerName: jhipster-registry
            type: aws.ecs.ContainerDefinitionSpec
            image: jhipster/jhipster-registry:v4.0.2
            cpu: 1024
            softMemoryLimit: 768
            portMappings:
            - name: port-mapping-8761
              type: aws.ecs.PortSpec
              containerPort: 8761
            environment:
              SPRING_PROFILES_ACTIVE: prod
              SPRING_SECURITY_USER_PASSWORD: admin # need to see how to secure secrets 
              JHIPSTER_REGISTRY_PASSWORD: admin
              JHIPSTER_SECURITY_AUTHENTICATION_JWT_SECRET: bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl
              SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE: native
              # SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS: file:./central-config
              EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS: 15
              EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS: 30
              EUREKA_SERVER_PEER_EUREKA_NODES_UPDATE_INTERVAL_MS: 15000
              EUREKA_SERVER_RENAWAL_THRESHOLD_UPDATE_INTERVAL_MS: 15000
              EUREKA_SERVER_REGISTRY_SYNC_RETRIES: 3
              EUREKA_SERVER_ENABLE_SELF_PRESERVATION: false
              EUREKA_SERVER_PEER_NODE_CONNECT_TIMEOUT_MS: 2000
              EUREKA_CLIENT_FETCH_REGISTRY: true
              EUREKA_CLIENT_REGISTER_WITH_EUREKA: true
              # JHIPSTER_LOGGING_LOGSTASH_ENABLED: true
              # JHIPSTER_LOGGING_LOGSTASH_HOST: jhipster-logstash
              # JHIPSTER_METRICS_LOGS_ENABLED: true
              # JHIPSTER_METRICS_LOGS_REPORTFREQUENCY: 60
            logConfiguration:
            - name: cloudwatch-log-registry
              type: aws.ecs.LogConfigurationSpec
              logDriver: awslogs
              options:
                awslogs-group: "/ecs/ecommerce"
                awslogs-region: "{{region}}"
                awslogs-stream-prefix: "ecs"

        - name: ecommerce-store-app
          type: aws.ecs.ServiceSpec
          serviceName: ecommerce-store-app
          desiredCount: 1
          launchType: FARGATE
          networkMode: awsvpc
          assignPublicIp: true
          executionRole: 'arn:aws:iam::932770550094:role/ecsTaskExecutionRole'
          cpu: 1024
          memory: 2048
          subnets:
          - 'Name:{{username}}-ecommerce-ecs-subnet-ipv4-az-1a'
          - 'Name:{{username}}-ecommerce-ecs-subnet-ipv4-az-1b'
          securityGroups:
          - 'Name:{{username}}-ecommerce-ecs-security-group'
          containerDefinitions:
          - name: ecommerce-store-app
            containerName: ecommerce-store-app
            type: aws.ecs.ContainerDefinitionSpec
            image: xebialabsunsupported/ecommerce-store
            cpu: 1024
            softMemoryLimit: 768
            portMappings:
            - name: port-mapping-8080
              type: aws.ecs.PortSpec
              containerPort: 8080
            logConfiguration:
            - name: cloudwatch-log-registry
              type: aws.ecs.LogConfigurationSpec
              logDriver: awslogs
              options:
                awslogs-group: "/ecs/ecommerce"
                awslogs-region: "{{region}}"
                awslogs-stream-prefix: "ecs"
            environment:
              SPRING_PROFILES_ACTIVE: prod,swagger
              JHIPSTER_REGISTRY_PASSWORD: admin
              SPRING_CLOUD_CONFIG_URI: http://admin:${jhipster.registry.password}@jhipster-registry:8761/config
              EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka
              SPRING_DATASOURCE_URL: jdbc:mysql://ecommerce-store-mysql:3306/store?useUnicode=true&characterEncoding=utf8&useSSL=false
              JHIPSTER_METRICS_LOGS_ENABLED: true
              # JHIPSTER_LOGGING_LOGSTASH_ENABLED: true
              # JHIPSTER_LOGGING_LOGSTASH_HOST: jhipster-logstash
              # SPRING_ZIPKIN_ENABLED: true
              # SPRING_ZIPKIN_BASE_URL: http://jhipster-zipkin
              # SPRING_SLEUTH_PROPAGATION_KEYS: x-request-id,x-ot-span-context
              JAVA_OPTS:  -Xmx256m -Xms256m
              # JHIPSTER_SLEEP: 30

        - name: ecommerce-store-db
          type: aws.ecs.ServiceSpec
          serviceName: ecommerce-store-db
          desiredCount: 1
          launchType: FARGATE
          networkMode: awsvpc
          assignPublicIp: true
          executionRole: 'arn:aws:iam::932770550094:role/ecsTaskExecutionRole'
          cpu: 1024
          memory: 2048
          subnets:
          - 'Name:{{username}}-ecommerce-ecs-subnet-ipv4-az-1a'
          - 'Name:{{username}}-ecommerce-ecs-subnet-ipv4-az-1b'
          securityGroups:
          - 'Name:{{username}}-ecommerce-ecs-security-group'
          containerDefinitions:
          - name: ecommerce-store-mysql
            containerName: ecommerce-store-mysql
            type: aws.ecs.ContainerDefinitionSpec
            image: mysql:5.7.20
            cpu: 1024
            softMemoryLimit: 768
            logConfiguration:
            - name: cloudwatch-log-registry
              type: aws.ecs.LogConfigurationSpec
              logDriver: awslogs
              options:
                awslogs-group: "/ecs/ecommerce"
                awslogs-region: "{{region}}"
                awslogs-stream-prefix: "ecs"
            command: 
            - mysqld
            - --lower_case_table_names=1 
            - --skip-ssl 
            - --character_set_server=utf8mb4 
            - --explicit_defaults_for_timestamp
            environment:
              MYSQL_USER: root
              MYSQL_ALLOW_EMPTY_PASSWORD: yes
              MYSQL_DATABASE: store

        - name: ecommerce-invoice-app
          type: aws.ecs.ServiceSpec
          serviceName: ecommerce-invoice-app
          desiredCount: 1
          launchType: FARGATE
          networkMode: awsvpc
          assignPublicIp: true
          executionRole: 'arn:aws:iam::932770550094:role/ecsTaskExecutionRole'
          cpu: 1024
          memory: 2048
          subnets:
          - 'Name:{{username}}-ecommerce-ecs-subnet-ipv4-az-1a'
          - 'Name:{{username}}-ecommerce-ecs-subnet-ipv4-az-1b'
          securityGroups:
          - 'Name:{{username}}-ecommerce-ecs-security-group'
          containerDefinitions:
          - name: ecommerce-invoice-app
            containerName: ecommerce-invoice-app
            type: aws.ecs.ContainerDefinitionSpec
            image: xebialabsunsupported/ecommerce-invoice
            cpu: 512
            softMemoryLimit: 768
            logConfiguration:
            - name: cloudwatch-log-registry
              type: aws.ecs.LogConfigurationSpec
              logDriver: awslogs
              options:
                awslogs-group: "/ecs/ecommerce"
                awslogs-region: "{{region}}"
                awslogs-stream-prefix: "ecs"
            environment:
              SPRING_PROFILES_ACTIVE: prod,swagger
              JHIPSTER_REGISTRY_PASSWORD: admin
              SPRING_CLOUD_CONFIG_URI: http://admin:${jhipster.registry.password}@jhipster-registry:8761/config
              EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka
              SPRING_DATASOURCE_URL: jdbc:mysql://ecommerce-invoice-mysql:3306/invoice?useUnicode=true&characterEncoding=utf8&useSSL=false
              JHIPSTER_METRICS_LOGS_ENABLED: true
              # JHIPSTER_LOGGING_LOGSTASH_ENABLED: true
              # JHIPSTER_LOGGING_LOGSTASH_HOST: jhipster-logstash
              # SPRING_ZIPKIN_ENABLED: true
              # SPRING_ZIPKIN_BASE_URL: http://jhipster-zipkin
              # SPRING_SLEUTH_PROPAGATION_KEYS: x-request-id,x-ot-span-context
              JAVA_OPTS:  -Xmx256m -Xms256m
              # JHIPSTER_SLEEP: 30
        - name: ecommerce-invoice-db
          type: aws.ecs.ServiceSpec
          serviceName: ecommerce-invoice-db
          desiredCount: 1
          launchType: FARGATE
          networkMode: awsvpc
          assignPublicIp: true
          executionRole: 'arn:aws:iam::932770550094:role/ecsTaskExecutionRole'
          cpu: 1024
          memory: 2048
          subnets:
          - 'Name:{{username}}-ecommerce-ecs-subnet-ipv4-az-1a'
          - 'Name:{{username}}-ecommerce-ecs-subnet-ipv4-az-1b'
          securityGroups:
          - 'Name:{{username}}-ecommerce-ecs-security-group'
          containerDefinitions:
          - name: ecommerce-invoice-mysql
            containerName: ecommerce-invoice-mysql
            type: aws.ecs.ContainerDefinitionSpec
            image: mysql:5.7.20
            cpu: 512
            softMemoryLimit: 768
            logConfiguration:
            - name: cloudwatch-log-registry
              type: aws.ecs.LogConfigurationSpec
              logDriver: awslogs
              options:
                awslogs-group: "/ecs/ecommerce"
                awslogs-region: "{{region}}"
                awslogs-stream-prefix: "ecs"
            command: 
            - mysqld 
            - --lower_case_table_names=1 
            - --skip-ssl 
            - --character_set_server=utf8mb4 
            - --explicit_defaults_for_timestamp
            environment:
              MYSQL_USER: root
              MYSQL_ALLOW_EMPTY_PASSWORD: yes
              MYSQL_DATABASE: invoice

        - name: ecommerce-notification-app
          type: aws.ecs.ServiceSpec
          serviceName: ecommerce-notification-app
          desiredCount: 1
          launchType: FARGATE
          networkMode: awsvpc
          assignPublicIp: true
          executionRole: 'arn:aws:iam::932770550094:role/ecsTaskExecutionRole'
          cpu: 1024
          memory: 2048
          subnets:
          - 'Name:{{username}}-ecommerce-ecs-subnet-ipv4-az-1a'
          - 'Name:{{username}}-ecommerce-ecs-subnet-ipv4-az-1b'
          securityGroups:
          - 'Name:{{username}}-ecommerce-ecs-security-group'
          containerDefinitions:
          - name: ecommerce-notification-app
            containerName: ecommerce-notification-app
            type: aws.ecs.ContainerDefinitionSpec
            image: xebialabsunsupported/ecommerce-notification
            cpu: 512
            softMemoryLimit: 768
            logConfiguration:
            - name: cloudwatch-log-registry
              type: aws.ecs.LogConfigurationSpec
              logDriver: awslogs
              options:
                awslogs-group: "/ecs/ecommerce"
                awslogs-region: "{{region}}"
                awslogs-stream-prefix: "ecs"
            environment:
              SPRING_PROFILES_ACTIVE: prod,swagger
              JHIPSTER_REGISTRY_PASSWORD: admin
              SPRING_CLOUD_CONFIG_URI: http://admin:${jhipster.registry.password}@jhipster-registry:8761/config
              EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka
              SPRING_DATA_MONGODB_URI: mongodb://ecommerce-notification-mongodb:27017
              SPRING_DATA_MONGODB_DATABASE: notification
              JHIPSTER_METRICS_LOGS_ENABLED: true
              # JHIPSTER_LOGGING_LOGSTASH_ENABLED: true
              # JHIPSTER_LOGGING_LOGSTASH_HOST: jhipster-logstash
              # SPRING_ZIPKIN_ENABLED: true
              # SPRING_ZIPKIN_BASE_URL: http://jhipster-zipkin
              # SPRING_SLEUTH_PROPAGATION_KEYS: x-request-id,x-ot-span-context
              JAVA_OPTS:  -Xmx256m -Xms256m
              # JHIPSTER_SLEEP: 30

        - name: ecommerce-notification-db
          type: aws.ecs.ServiceSpec
          serviceName: ecommerce-notification-db
          desiredCount: 1
          launchType: FARGATE
          networkMode: awsvpc
          assignPublicIp: true
          executionRole: 'arn:aws:iam::932770550094:role/ecsTaskExecutionRole'
          cpu: 1024
          memory: 2048
          subnets:
          - 'Name:{{username}}-ecommerce-ecs-subnet-ipv4-az-1a'
          - 'Name:{{username}}-ecommerce-ecs-subnet-ipv4-az-1b'
          securityGroups:
          - 'Name:{{username}}-ecommerce-ecs-security-group'
          containerDefinitions:
          - name: ecommerce-notification-mongodb
            containerName: ecommerce-notification-mongodb
            type: aws.ecs.ContainerDefinitionSpec
            image: mongo:3.6.3
            cpu: 512
            softMemoryLimit: 768
            logConfiguration:
            - name: cloudwatch-log-registry
              type: aws.ecs.LogConfigurationSpec
              logDriver: awslogs
              options:
                awslogs-group: "/ecs/ecommerce"
                awslogs-region: "{{region}}"
                awslogs-stream-prefix: "ecs"